clean /opt/puavo-os-extra too

diff --git a/puavo-image-extend b/puavo-image-extend
--- a/puavo-image-extend
+++ b/puavo-image-extend
@@ -89,28 +89,32 @@ puavo_patch(){
     PLACE=opt/puavo-os-extra
 
     #copy data to chroot
-    echo "info: copy patch to chroot"
+    echo "info: copy patchdir to chroot" 1>&2
     mkdir -p $CHROOT/$PLACE
     cp -r $1/* $CHROOT/$PLACE
 
     #copy cached apt to chroot
-    echo "info: copy apt from cache to chroot"
+    echo "info: copy apt from cache to chroot"                                           1>&2
     rsync -ra  --size-only ./cache/apt/ $CHROOT/var/cache/apt/archives/.
 
     # do chroot
+    echo "info: enter chroot"                                                            1>&2
     echo "run-parts --regex=\"^[0-9]{2}-.*$\" /$PLACE" | puavo_chroot $CHROOT
     if test $? -ne 0;then
-       echo "could not patch \"$1\""
+       echo "could not patch \"$1\""                                                     1>&2
        exit 1
     fi
+    echo "info: exit chroot"                                                             1>&2
 
     # copyback apt and clean chroot
-    echo "info: update apt cache"
-    rsync -rav  --delete --size-only  $CHROOT/var/cache/apt/archives/ ./cache/apt/
-    echo "info: remove apt in chroot"
+    echo "info: update apt cache"                                                        1>&2
+    rsync -rav  --delete --size-only  $CHROOT/var/cache/apt/archives/ ./cache/apt/       1>&2
+    echo "info: remove apt in chroot"                                                    1>&2
     rm -r $CHROOT/var/cache/apt/archives/*
 
-    #rm -r $CHROOT/opt/puavo-os-extra
+    rm -r $CHROOT/$PLACE
+    cp -r $1/* $CHROOT/$PLACE
+    
 }
 
 puavo_image_name(){
@@ -148,14 +152,17 @@ puavo_image(){
 ###################################################################################
 ###################################################################################
 
+OSNAME=""
+CLASS=""
+
 if test -f /etc/puavo-image/name; then
     CURRENT_IMAGE=$(cat /etc/puavo-image/name)
     OSNAME=$(echo $CURRENT_IMAGE|cut -d- -f1-2)
     CLASS=$(echo $CURRENT_IMAGE|cut -d- -f3)
 fi
 
-test "$OSNAME" = "opinsys-os" -o "$OSNAME"= "" && OSNAME="puavo-os"
-test "$CLASS" = "" && CLASS="standard"
+test "$OSNAME"="opinsys-os" -o "$OSNAME"="" && OSNAME="puavo-os"
+test -z "$CLASS"  && CLASS="standard"
 
 
 while [ $# -gt 0 ]; do
